language: cpp
os: linux
dist: bionic
compiler:
  - gcc
  - clang

install:
  - cmake -D CMAKE_INSTALL_LIBDIR=lib .

script:
  - make channel_test11 && ./tests/channel_test11
  - make channel_test14 && ./tests/channel_test14
  - make channel_test17 && ./tests/channel_test17
